version: '{build}'
branches:
  only:
  - master
image: 
 - Visual Studio 2017
# - Ubuntu
configuration: Release
environment:
  kek:
    secure: 7K1T/yYywk+v49LE9icYk1umcP/6b9dL8hYE2Cg8HXMsTdjG9otMM0VMsHbcF0gE
install:
  - ps: | 
     # kek will not be decrypted for PR builds.
     if (Test-Path ENV:kek) {
       iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
       dotnet "appveyor-tools/secure-file.dll" -decrypt src/FluentValidation-Release.snk.enc -secret $ENV:kek
     }
     if (($PSVersionTable.PSVersion.Major -le 5) -or $IsWindows) {
      $urlCurrent = "https://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.2.100-preview1-009349/dotnet-sdk-2.2.100-preview1-009349-win-x64.zip"
      $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetsdk"
      mkdir $env:DOTNET_INSTALL_DIR -Force | Out-Null
      $tempFileCurrent = [System.IO.Path]::GetTempFileName()
      (New-Object System.Net.WebClient).DownloadFile($urlCurrent, $tempFileCurrent)
      Add-Type -AssemblyName System.IO.Compression.FileSystem; [System.IO.Compression.ZipFile]::ExtractToDirectory($tempFileCurrent, $env:DOTNET_INSTALL_DIR)
      $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"
     }

build_script:
 - ps: ./build.ps1
test: off
artifacts:
  - path: '.build/packages/*.nupkg'
  - path: '.build/Release'
    type: zip
notifications:
- provider: Email
  to:
  - jeremy@jeremyskinner.co.uk
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
skip_commits:
  files:
    - docs/